#!/bin/sh


    inst="thymiosuite"    
    app="org.mobsya.ThymioSuite"

    test -d $inst && rm -r $inst
    mkdir -p $inst
    
    mkdir -p /etc/flatpak/installations.d
    cat <<EOF > /etc/flatpak/installations.d/$inst.conf
[Installation "$inst"]
Path=$(pwd)/$inst
DisplayName=$inst
StorageType=harddisk
EOF

    flatpak  --installation=$inst --if-not-exists remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
    flatpak  --installation=$inst --assumeyes --noninteractive install flathub $app

    rm /etc/flatpak/installations.d/$inst.conf

    tar -czf $inst.tgz $inst
#    rm -r $inst



